spring.application.name=secondBrain
spring.datasource.url = jdbc:postgresql://localhost:5433/secondbrain
spring.datasource.username = postgres
spring.datasource.password = rudra
secret.key.jwt = mySuperSecretKeyForJwtGeneration123456789012345
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=localhost
spring.data.redis.port=6379
groq.api.key=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
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG
logging.level.com.fasterxml.jackson=DEBUG
baai-bge-3-read =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